### ISSUE TITLE
Typo in scientific notation example

### ISSUE THREAD

**Issue by ivan-m** [groovy-tutorial/groovy-tutorial#7]
At least in the web version, your usage of `{$$}1.49597870700 * 10^11{/$$}` is incorrect: it renders as `(... * 10^1) 1` (parentheses added).  The proper LaTeX markup would be `* 10^{11}`, though I'm not sure how this would play with the seeming usage of braces for indicating markup.

**Comment by dedickinson** [comment]
Thanks Ivan - your syntax worked fine. I've pushed through an update.

See: https://leanpub.com/groovytutorial/read#leanpub-auto-scientific-notation
